name 'efroese-cosign'
version '0.0.1'
author 'Erik Froese <erik.froese@gmail.com>'
summary 'Install the Cosign SSO in Apache.'
description 'Install the Cosign SSO module in Apache Httpd an configure consign authentication.'
license 'Apache'
project_page 'http://github/com/efroese/puppet-cosign'
dependency 'efroese/apache', '>= 1.0.0'
